# Totally Legal Front Runner {#Rebalancing-speculation}

#### Keywords

Machine learning, natural language processing, front-running.

## Alpha is fading

ETFs and passive funds have become popular in recent years due to the low cost and good diversification. Several studies have found that the majority of active funds could not generate higher-than-market return over the long run; the high management fee and tax can further decrease investors' net returns. Even if a skilled active manager could consistently identify and profit from market inefficiencies, the performance could still be hindered by the market's irrationality and black swan events.

This project aims to leverage data science techniques to develop an active trading strategy to help asset managers generate better returns by predicting the behavior of passively managed funds.

## How to train your model

This project will help active fund managers understand the behavior of their passive counterparts, predict their trades and earn profit by "front running" them. 

Due to the complexity of bond market, our project will only focus on equity funds at this time. The detailed steps are listed below.

1. Gather features of target funds' investment mandate. The features should consider the following questions: What is the investment mandate, the return target and risk appetite? What is the benchmark? How detailed (?) is the historical tracking record? What is the weighting scheme and how often does the rebalance happen? The investment mandate can be retrieved from each fund's website or through Bloomberg terminal (with a substential subscription fee). Natural language processing techniques can be leveraged to quickly process large numbers of unstructured PDF files.

2. Get the daily / monthly (depending on data availability) position files of each target fund. Compare the position changes and tag the securities that have been bought / sold.

3. Retrieve the features of actively traded securities (segments, historical performance, risk, etc.), e.g. the Russell 3000 universe.

4. Train a model to predict if target funds would buy / sell the securities. Based on the rebalancing results, group the securities into three groups (bought, sold, hold). Use machine learning techniques to classify these securities, then use resampling methods (bootstrap, cross validation) to choose the model with the lowest test error.

5. Determine if the strategy is profitable through simulation. Set up paper portfolios that "front run" the predicted trades. Evaluate the strategy's P&L, taking into consideration trading cost and taxes.

6. Trade! However, don't lay all your faith in the model. Always monitor and control your exposures.


## The end

This project would help active mangers generate alpha in the short term. However, just as any other game, whenever a new strategy gains some edge, a counter strategy will come into place sooner or later. Even if there is no counter strategy and this strategy continues to make a lot of profit, it could be easily copied by other investors, which would lead to higher execution cost, lower expected profit, and more dangerously, higher price volatility around balancing periods.

Nevertheless, the tool developed in step 1 & 2 could serve as a powerful tool for investors, educators and researchers to easily get summarized information from a large pool of ETFs and mutual funds.
